name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -   name: Setup SSH Keys and known_hosts
          env:
                 SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          run: |
                ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
 
      - name: Add remote 
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://ugursirvermez:$HF@huggingface.co/spaces/ugursirvermez/FoodVision101
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://ugursirvermez:$HF@huggingface.co/spaces/ugursirvermez/FoodVision101 main
